services:
  db:
    image: postgres:14-alpine
    restart: unless-stopped
    command: postgres -c 'max_connections=100'
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./logs/db:/var/log/postgresql
    environment:
      - POSTGRES_DB=wklejka
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=haslo123

  cache:
    image: redis:6.2.6-alpine
    restart: unless-stopped
    volumes:
      - ./data/cache:/data
      - ./logs/dev/cache:/var/log/redis
    environment:
      - REDIS_DB=0

  backend:
    build: ./Backend
    restart: unless-stopped
    environment:
      - WKLEJKA_PROD=True
    volumes:
      - ./logs/backend:/var/log/django
      - ./data/user_media:/var/www/wklejka/user_media
    expose:
      - "80"
    depends_on:
      - db
      - cache
    init: true

  frontend:
    build: ./Frontend
    restart: unless-stopped
    volumes:
      - ./logs/frontend:/var/log/nginx
      - ./data/user_media:/var/www/wklejka/user_media
    ports:
      - "80:80"
    depends_on:
      - backend
