services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=wklejka
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=haslo123
  backend:
    build: ./Backend
    expose:
      - "8000"
    depends_on:
      - db
  frontend:
    build: ./Frontend
    ports:
      - "80:80"
    depends_on:
      - backend
