services:
  db:
    image: postgres:14-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./logs/dev/db:/var/log/postgresql
    environment:
      - POSTGRES_DB=wklejka
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=haslo123

  backend:
    build: ./Backend
    volumes:
      - ./Backend:/code
      - ./logs/dev/backend:/var/log/django
      - ./data/user_media:/var/www/wklejka/user_media
    ports:
      - "80:80"
    depends_on:
      - db
    init: true
