[tool.black]
line-length = 88
skip-string-normalization = true
extend-exclude =  '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | migrations
)/
'''


[tool.isort]
profile = "black"
atomic = true
combine_star = true
honor_noqa = true
lines_before_imports = 1
default_section = "THIRDPARTY"
# Headings
import_heading_future = "Future"
import_heading_stdlib = "Standard Library"
import_heading_django = "Django"
import_heading_thirdparty = "3rd-Party"
import_heading_firstparty = "Project"
import_heading_localfolder = "Local"
known_django = "django"
# Order
sections = ["FUTURE","STDLIB","DJANGO","THIRDPARTY","FIRSTPARTY","LOCALFOLDER"]


[tool.mypy]
python_version = "3.8"
mypy_path = "./backend"
ignore_missing_imports = true
ignore_missing_imports_per_module = true
disallow_any_generics = true
disallow_untyped_defs = true
no_implicit_optional = true
no_strict_optional = true
no_warn_no_return = true
warn_unreachable = true
allow_untyped_globals = true
allow_redefinition = true
show_error_context = true
show_error_codes = true
show_column_numbers = true
exclude = '''
(?x)
(
    migrations
    | manage.py
)
'''
plugins = ["mypy_django_plugin.main"]

[tool.django-stubs]
django_settings_module = "Backend.settings"
