# Generated by Django 4.0.3 on 2022-04-07 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wklejki', '0008_attachment_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthMeta',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='auth', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_verified', models.BooleanField(default=False)),
                ('token', models.CharField(blank=True, max_length=64)),
            ],
        ),
    ]
