# Generated by Django 4.0.3 on 2022-04-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paste_token_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authmeta',
            name='token',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
