# Generated by Django 4.0.3 on 2022-03-30 17:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wklejki', '0005_alter_paste_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='paste',
            name='likers',
            field=models.ManyToManyField(blank=True, related_name='liked_pastes', to=settings.AUTH_USER_MODEL),
        ),
    ]
