# Generated by Django 4.0.3 on 2022-03-31 12:22

from django.db import migrations, models
import django.db.models.deletion
import wklejki.models


class Migration(migrations.Migration):

    dependencies = [
        ('wklejki', '0006_paste_likers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=wklejki.models.get_attachment_upload_location)),
                ('name', models.TextField(max_length=100)),
                ('paste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='wklejki.paste')),
            ],
        ),
    ]
