# Generated by Django 4.0.3 on 2022-03-31 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wklejki', '0007_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
