# Generated by Django 4.0.3 on 2022-04-10 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wklejki', '0009_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='reviewed_by',
        ),
    ]
