# Generated by Django 4.0.4 on 2022-05-11 19:24

from django.db import migrations, models
import wklejki.models


class Migration(migrations.Migration):

    dependencies = [
        ('wklejki', '0011_paste_expire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.FileField(null=True, upload_to=wklejki.models.get_pfp_upload_location),
        ),
        migrations.AddField(
            model_name='customuser',
            name='description',
            field=models.TextField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='paste',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
