# Generated by Django 4.0.4 on 2022-05-13 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wklejki', '0012_customuser_avatar_customuser_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='paste',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='pastes', to='wklejki.tag'),
        ),
    ]
